name: Maestro Test

on:
  push:
    branches:
      - hanyu_test_maestro

jobs:
  Auto_Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '23'

      # Install all dependencies (from package.json in sync-trip)
      - name: Install Dependencies
        working-directory: ./sync-trip
        run: npm install

      - name: Authenticate with Expo
        working-directory: ./sync-trip
        run: npx expo login -u ${{ secrets.EXPO_USERNAME }} -p ${{ secrets.EXPO_PASSWORD }}

      # Install Maestro CLI
      - name: Install Maestro CLI
        working-directory: ./sync-trip
        run: |
          curl -fsSL "https://get.maestro.mobile.dev" | bash
          export PATH="$PATH":"$HOME/.maestro/bin"
          maestro --version

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Init eas
        working-directory: ./sync-trip
        run: eas init

      - name: Build Configure
        working-directory: ./sync-trip
        run: eas build:configure --platform android

      - name: Start Android Emulator & Test
        env:
          ANDROID_EMULATOR_WAIT_TIME_BEFORE_KILL: 120
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          profile: pixel_4a
          arch: arm64-v8a
          force-avd-creation: false
          avd-name: macOS-avd-arm64-v8a-31
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: |
            cd ./sync-trip
            npx expo start
            maestro test dashboardScreen_test.yaml
